version: '3'

networks: 
  csv-dev-network:

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: csv_phpmyadmin
    restart: always
    ports: 
      - "8088:80"
    environment:
      PMA_HOSTS: mysql_database
      MYSQL_ROOT_PASSWORD: Dev123
    depends_on: 
      - mysql_database
    networks: 
      - csv-dev-network

  mysql_database:
    image: mysql:8.0
    container_name: csv_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: csv_database
      MYSQL_ROOT_PASSWORD: Dev123
      SERVICE_TAGS: dev
      SERVICE_NAME: csv_database
    networks: 
      - csv-dev-network
